"""
blog.py — Blog publisher for Pressroom.

This publisher is responsible for posting published papers to a blog platform.
It converts the paper content to blog-postable format and submits via API.

DESIGN RATIONALE:
- Blog publisher handles the "post to blog" step of multi-format publishing
- Uses blog CMS API (e.g., WordPress, Medium, Ghost) to create posts
- Content is derived from the generated PDF's frontmatter + body markdown
- Supports draft/published states matching the paper's gate

SPEC REFERENCE: §11.4 "Blog Publisher — Blog CMS Integration"
         §11.4.1 "Blog API Requirements" (content format, authentication)

DEPENDENCIES:
- This file implements: Publisher protocol from base.py
- Imported by: services/publishers/base.py (get_publisher factory)

PUBLISH WORKFLOW:
1. User clicks Publish in UI
2. PDF is generated by PandocEngine/SileEngine
3. Blog publisher converts markdown content to blog post format
4. Posts to blog CMS via API (requires API key stored in env vars)

TODO: Implement the full BlogPublisher class (see module docstring for design)

USAGE IN ROUTERS:
    publisher = get_publisher("blog")
    result = await publisher.publish(
        pdf_path=Path("/tmp/pressroom/my-paper/output.pdf"),
        metadata={"slug": "my-paper", "title": "My Paper", "body": "# Heading\\n\\nContent..."}
    )
    # Returns: {"posted_to": "https://blog.example.com/post/my-paper"}
"""

from pathlib import Path
from typing import Any, Dict


class BlogPublisher:
    """
    Blog publisher that posts to a blog CMS via API.

    TODO: Implement the full BlogPublisher class (see module docstring for design)

    INTEGRATION POINTS:
    - Called by routers/publish.py publish_paper() endpoint after PDF generation
    - Requires blog_api_key from config (stored in environment variable)
    """

    async def publish(
        self,
        pdf_path: Path,
        metadata: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Post paper content to blog CMS.

        PARAMETERS:
        - pdf_path: Path to the generated PDF file (for reference)
        - metadata: Dict with paper metadata (slug, title, body, gate, author, etc.)

        RETURNS:
        - dict with keys: posted_to (URL of blog post)

        SIDE EFFECTS:
        - Creates new blog post via CMS API
        - If gate is "draft", posts as draft; if "published", posts publicly
        - Returns URL for reference by UI

        BLOG POST FORMAT:
            Title: frontmatter["title"]
            Content: frontmatter["body"] (markdown to HTML conversion)
            Tags: [gate, version, author]
            Status: "draft" if gate != "published", else "publish"

        TODO: Implement:
        1. Read blog API configuration from config (BLOG_API_URL, BLOG_API_KEY)
        2. Convert markdown body to HTML (use markdown library or pandoc)
        3. Build blog post payload:
           {
               "title": metadata["title"],
               "content": html_content,
               "status": "draft" if metadata.get("gate") != "published" else "publish",
               "tags": [metadata.get("gate", "alpha"), metadata.get("version", "")]
           }
        4. POST to blog CMS API
        5. Return {"posted_to": response["url"]}

        BLOG CMS SUPPORT:
        - WordPress (REST API)
        - Ghost (API v2+)
        - Medium (API)
        - Custom (via configurable endpoint)

        ERROR HANDLING:
        - If blog API key invalid, raise AuthenticationError
        - If blog API unreachable, raise ConnectionError
        - If blog post creation fails, raise BlogPublishError
        """
        pass