"""
docx.py — DOCX publisher for Pressroom.

This publisher is responsible for converting the generated PDF to DOCX (Word) format
and saving it to the local pressroom-pubs directory structure.

DESIGN RATIONALE:
- DOCX publisher provides Word-compatible output from the same PDF content
- Uses LibreOffice or pandoc for PDF-to-DOCX conversion
- Output follows same versioned snapshot naming as PDF publisher
- Allows users to share drafts with collaborators who prefer Word

SPEC REFERENCE: §11.5 "DOCX Publisher — Word Document Export"
         §11.5.1 "Conversion Method" (LibreOffice CLI or pandoc)

DEPENDENCIES:
- This file implements: Publisher protocol from base.py
- Imported by: services/publishers/base.py (get_publisher factory)

PUBLISH WORKFLOW:
1. User clicks Publish in UI
2. PDF is generated by PandocEngine/SileEngine
3. DOCX publisher converts PDF to DOCX format
4. Saves to /app/data/pubs/{user_id}/{slug}/{version}/output.docx

TODO: Implement the full DocxPublisher class (see module docstring for design)

USAGE IN ROUTERS:
    publisher = get_publisher("docx")
    result = await publisher.publish(
        pdf_path=Path("/tmp/pressroom/my-paper/output.pdf"),
        metadata={"slug": "my-paper", "version": "v0.1-alpha", "gate": "alpha"}
    )
    # Returns: {"saved_to": "/app/data/pubs/user_abc/my-paper/v0.1-alpha/output.docx"}
"""

from pathlib import Path
from typing import Any, Dict


class DocxPublisher:
    """
    DOCX publisher that converts PDF to Word format.

    TODO: Implement the full DocxPublisher class (see module docstring for design)

    INTEGRATION POINTS:
    - Called by routers/publish.py publish_paper() endpoint after PDF generation
    - Called by routers/papers.py save_paper() when user requests Word export
    """

    async def publish(
        self,
        pdf_path: Path,
        metadata: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Convert PDF to DOCX and save to pressroom-pubs directory.

        PARAMETERS:
        - pdf_path: Path to the generated PDF file
        - metadata: Dict with paper metadata (slug, version, gate, author, etc.)

        RETURNS:
        - dict with keys: saved_to (absolute path where DOCX was saved)

        SIDE EFFECTS:
        - Creates directory /app/data/pubs/{user_id}/{slug}/{version}/ if needed
        - Converts PDF to DOCX using LibreOffice or pandoc CLI
        - Saves to {pubs_dir}/{slug}/{version}/output.docx

        SNAPSHOT PATH PATTERN (from SPEC §6):
            /app/data/pubs/{user_id}/{slug}/{version}/output.docx
        
        EXAMPLE:
            /app/data/pubs/user_abc123/my-great-idea/v0.1-alpha/output.docx

        CONVERSION METHODS:
        1. LibreOffice CLI (recommended):
           libreoffice --headless --convert-to docx --outdir /output/dir input.pdf
        2. Pandoc (alternative):
           pandoc input.pdf -o output.docx
        
        TODO: Implement:
        1. Extract slug and version from metadata
        2. Create output directory: /app/data/pubs/{user_id}/{slug}/{version}/
        3. Convert PDF to DOCX using subprocess:
           - Try libreoffice first
           - Fall back to pandoc if libreoffice not available
        4. Save to output.docx
        5. Return {"saved_to": str(abs_path)}

        ERROR HANDLING:
        - If PDF file doesn't exist, raise FileNotFoundError
        - If conversion fails (neither libreoffice nor pandoc available), raise ConversionError
        - If directory creation fails, raise PermissionError
        """
        pass