"""
pdf.py — PDF publisher for Pressroom.

This publisher is responsible for saving the generated PDF to the local
pressroom-pubs directory structure and optionally mirroring to the
GitHub pressroom-pubs repository.

DESIGN RATIONALE:
- PDF publisher handles the final step of the publish workflow
- Files are saved locally first, then mirrored to GitHub
- Versioned snapshot naming follows SPEC §6 pattern

SPEC REFERENCE: §11.3 "PDF Publisher — Local Filesystem Storage"
         §6 "Versioned Snapshot Naming" (snapshot path pattern)

DEPENDENCIES:
- This file implements: Publisher protocol from base.py
- Imported by: services/publishers/base.py (get_publisher factory)

PUBLISH WORKFLOW:
1. User clicks Publish in UI
2. Router calls task_queue.submit() with publish_paper function
3. PDF is generated by PandocEngine/SileEngine
4. PDF publisher saves to /app/data/pubs/{user_id}/{slug}/{version}/
5. If mirror enabled, pushes to pressroom-pubs GitHub repo

TODO: Implement the full PdfPublisher class (see module docstring for design)

USAGE IN ROUTERS:
    publisher = get_publisher("pdf")
    result = await publisher.publish(
        pdf_path=Path("/tmp/pressroom/my-paper/output.pdf"),
        metadata={"slug": "my-paper", "version": "v0.1-alpha", "gate": "alpha"}
    )
    # Returns: {"saved_to": "/app/data/pubs/user_abc/my-paper/v0.1-alpha/output.pdf"}
"""

from pathlib import Path
from typing import Any, Dict


class PdfPublisher:
    """
    PDF publisher that saves to local filesystem.

    TODO: Implement the full PdfPublisher class (see module docstring for design)

    INTEGRATION POINTS:
    - Called by routers/publish.py publish_paper() endpoint after PDF generation
    - Called by services/snapshot.py create_snapshot() for mirror step
    """

    async def publish(
        self,
        pdf_path: Path,
        metadata: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Save a generated PDF into the local pressroom-pubs directory structure.

        PARAMETERS:
        - pdf_path: Path to the generated PDF file (must already exist)
        - metadata: Dict with paper metadata — required keys:
            - slug (str):    URL-friendly paper identifier
            - version (str): Version string e.g. "v0.1-alpha"
            - user_id (str): Authenticated user's ID

        RETURNS:
        - dict: {"saved_to": "<absolute path of the copied PDF>"}

        SIDE EFFECTS:
        - Creates /app/data/pubs/{user_id}/{slug}/{version}/ if it doesn't exist
        - Copies the PDF to that directory as {slug}.pdf

        SNAPSHOT PATH (SPEC §6):
            /app/data/pubs/{user_id}/{slug}/{version}/{slug}.pdf

        RAISES:
        - FileNotFoundError: if pdf_path does not exist
        - KeyError: if required metadata keys are missing
        """
        import shutil

        if not pdf_path.exists():
            raise FileNotFoundError(f"PDF not found at {pdf_path}")

        # Extract required metadata
        slug     = metadata["slug"]
        version  = metadata["version"]
        user_id  = metadata["user_id"]

        # Build destination directory and copy
        dest_dir = Path("/app/data/pubs") / user_id / slug / version
        dest_dir.mkdir(parents=True, exist_ok=True)

        dest_path = dest_dir / f"{slug}.pdf"
        shutil.copy2(pdf_path, dest_path)

        return {"saved_to": str(dest_path)}