"""
pdf.py — PDF publisher for Pressroom.

This publisher is responsible for saving the generated PDF to the local
pressroom-pubs directory structure and optionally mirroring to the
GitHub pressroom-pubs repository.

DESIGN RATIONALE:
- PDF publisher handles the final step of the publish workflow
- Files are saved locally first, then mirrored to GitHub
- Versioned snapshot naming follows SPEC §6 pattern

SPEC REFERENCE: §11.3 "PDF Publisher — Local Filesystem Storage"
         §6 "Versioned Snapshot Naming" (snapshot path pattern)

DEPENDENCIES:
- This file implements: Publisher protocol from base.py
- Imported by: services/publishers/base.py (get_publisher factory)

PUBLISH WORKFLOW:
1. User clicks Publish in UI
2. Router calls task_queue.submit() with publish_paper function
3. PDF is generated by PandocEngine/SileEngine
4. PDF publisher saves to /app/data/pubs/{user_id}/{slug}/{version}/
5. If mirror enabled, pushes to pressroom-pubs GitHub repo

TODO: Implement the full PdfPublisher class (see module docstring for design)

USAGE IN ROUTERS:
    publisher = get_publisher("pdf")
    result = await publisher.publish(
        pdf_path=Path("/tmp/pressroom/my-paper/output.pdf"),
        metadata={"slug": "my-paper", "version": "v0.1-alpha", "gate": "alpha"}
    )
    # Returns: {"saved_to": "/app/data/pubs/user_abc/my-paper/v0.1-alpha/output.pdf"}
"""

from pathlib import Path
from typing import Any, Dict


class PdfPublisher:
    """
    PDF publisher that saves to local filesystem.

    TODO: Implement the full PdfPublisher class (see module docstring for design)

    INTEGRATION POINTS:
    - Called by routers/publish.py publish_paper() endpoint after PDF generation
    - Called by services/snapshot.py create_snapshot() for mirror step
    """

    async def publish(
        self,
        pdf_path: Path,
        metadata: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Save PDF to local pressroom-pubs directory.

        PARAMETERS:
        - pdf_path: Path to the generated PDF file
        - metadata: Dict with paper metadata (slug, version, gate, author, etc.)

        RETURNS:
        - dict with keys: saved_to (absolute path where PDF was saved)

        SIDE EFFECTS:
        - Creates directory /app/data/pubs/{user_id}/{slug}/{version}/ if needed
        - Copies PDF to {pubs_dir}/{slug}/{version}/output.pdf
        - Returns absolute path for reference by mirror step

        SNAPSHOT PATH PATTERN (from SPEC §6):
            /app/data/pubs/{user_id}/{slug}/{version}/output.pdf
        
        EXAMPLE:
            /app/data/pubs/user_abc123/my-great-idea/v0.1-alpha/output.pdf

        TODO: Implement:
        1. Extract slug and version from metadata
        2. Create pubs directory: Path("/app/data/pubs")
        3. Create user subdirectory: /app/data/pubs/{user_id} (from auth)
        4. Create paper subdirectory: /{slug}/{version}/
        5. Copy PDF to output.pdf
        6. Return {"saved_to": str(abs_path)}

        ERROR HANDLING:
        - If PDF file doesn't exist, raise FileNotFoundError
        - If directory creation fails, raise PermissionError
        """
        pass